# SPDX-License-Identifier: MIT-0
---
# tasks file for deploy_traefik
- name: Ensures traefik dir exists
  ansible.builtin.file:
    path: "{{ traefik_dir }}"
    state: directory
    owner: "{{ user }}"
    group: "{{ group }}"
    mode: "0700"


- name: Ensures acme.json file exists
  ansible.builtin.file:
    path: "{{ traefik_dir }}/acme.json"
    state: touch
    mode: "0600"


- name: Adding traefik.yml file
  ansible.builtin.template:
    src: traefik.yml.j2
    dest: "{{ traefik_dir }}/traefik.yml"
    mode: "0600"


- name: Create the traefik network
  community.docker.docker_network:
    name: traefik


- name: Create the backend network
  community.docker.docker_network:
    name: backend


- name: Create the traefik container
  community.docker.docker_container:
    name: traefik
    env_file: .env
    image: traefik:latest
    restart_policy: unless-stopped
    recreate: true
    networks:
      - name: traefik
      - name: backend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "{{ traefik_dir }}/traefik.yml:/etc/traefik/traefik.yml"
      - "{{ traefik_dir }}/acme.json:/acme.json"
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      traefik.enable: "true"
      traefik.http.routers.traefik.rule: "Host(`{{ traefik_api_url }}`)"
      traefik.http.routers.traefik.entrypoints: "websecure"
      traefik.http.routers.traefik.service: "api@internal"
      traefik.http.routers.traefik.middlewares: "auth"
      traefik.http.middlewares.auth.basicauth.users: "{{ traefik_api_user }}:{{ traefik_api_password | password_hash('blowfish', '1234567890123456789012') }}"
